# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AddressBook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AddressBook
pod 'SwiftyJSON'

end
